-- Find My Rizq — seed data (REAL jobs pulled from the Arbeitnow public API).
-- Run: npx wrangler d1 execute find-my-rizq --remote --file=./migrations/0002_seed.sql

INSERT OR IGNORE INTO jobs
(dedup_key,source,external_id,title,company,description,location,country,salary,salary_min,salary_max,currency,job_type,category,tags,remote,lat,lng,apply_url,posted_at,first_seen,last_seen,status,clicks)
VALUES
('seed:1','arbeitnow','1','Senior Product Analyst','Flix','Be the analytical backbone of our Customer Experience stream. Own how we understand customers as they move through the Flix journey, and turn that into opportunities. Advanced SQL in Snowflake, A/B testing, and strong statistical literacy required. Hybrid, 45+ markets.','München, Bayern, Germany','','',NULL,NULL,'GBP','Full Time','Technology & IT','[]',0,48.1351,11.582,'https://www.arbeitnow.com/jobs/companies/flix/senior-product-analyst-munchen-21748',strftime('%s','now','-1 hours'),strftime('%s','now'),strftime('%s','now'),'live',0),
('seed:2','arbeitnow','2','AI Developer (LLM Products) – Remote','dexter health','Build AI-powered software for care teams to reduce admin workload in healthcare. Hands-on engineering: turn ambiguous product ideas into production-ready AI features. LLM workflows, structured outputs, evaluation loops. Daily use of Claude Code, Cursor, Copilot.','Cologne, Germany · Remote','','',NULL,NULL,'GBP','Full Time','Technology & IT','["Remote"]',1,NULL,NULL,'https://www.arbeitnow.com/jobs/companies/dexter-health/ai-developer-llm-products-remote-cologne-37116',strftime('%s','now','-2 hours'),strftime('%s','now'),strftime('%s','now'),'live',0),
('seed:3','arbeitnow','3','Freelance Bookkeeper & Finance Coordinator','LevelUp English','Berlin-based education company seeks a detail-oriented freelance bookkeeper to maintain financial organisation. Manage Spendesk, reconcile invoices, prepare monthly handovers for the tax advisor, and help build a lean, automation-driven finance function. Flexible hybrid working.','Berlin, Germany','','',NULL,NULL,'GBP','Contract','Finance & Accounting','[]',0,52.52,13.405,'https://www.arbeitnow.com/jobs/companies/levelup-english/freelance-bookkeeper-finance-coordinator-berlin-381385',strftime('%s','now','-3 hours'),strftime('%s','now'),strftime('%s','now'),'live',0),
('seed:4','arbeitnow','4','Founders Associate (Internship)','Reviven','Early-stage Berlin startup building a platform for acoustic manufacturers. Business development, pipeline building, market research and CRM. AI-native, enrolled in business/economics/engineering, strong communicator. Honest path to a permanent role.','Berlin, Germany','','€1,200/mo',NULL,NULL,'GBP','Internship','Sales & Marketing','[]',0,52.52,13.405,'https://www.arbeitnow.com/jobs/companies/reviven/founders-associate-internship-berlin-229941',strftime('%s','now','-4 hours'),strftime('%s','now'),strftime('%s','now'),'live',0),
('seed:5','arbeitnow','5','Senior Infrastructure Engineer','TecTake GmbH','Shape and operate the core IT infrastructure of a growing e-commerce company. Windows/Linux servers, virtualisation, Microsoft 365, Active Directory, Azure and Google cloud services, MFA/SSO, automation and scripting. On-prem and cloud.','Igersheim, Germany','','',NULL,NULL,'GBP','Full Time','Technology & IT','[]',0,49.575,9.74,'https://www.arbeitnow.com/jobs/companies/tectake-gmbh/senior-infrastructure-engineer-igersheim-284769',strftime('%s','now','-5 hours'),strftime('%s','now'),strftime('%s','now'),'live',0),
('seed:6','arbeitnow','6','Senior IT Consultant – PLM & CAD Systems','CONCAPE','Take technical ownership of CAD, PLM and CAM applications for an international electronics and drive-technology firm. Consulting, requirements management, project and release management, 2nd-level support steering. Creo, CATIA or Windchill experience ideal.','Bodensee, Germany','','',NULL,NULL,'GBP','Full Time','Engineering','[]',0,47.66,9.18,'https://www.arbeitnow.com/jobs/companies/concape/senior-it-consultant-plm-cad-systems-a-100-raum-bodensee-deutschland-munich-42266',strftime('%s','now','-6 hours'),strftime('%s','now'),strftime('%s','now'),'live',0),
('seed:7','arbeitnow','7','Account & Sales Manager (East Germany)','Ing Plus AG','Specialist in intelligent process automation for civil engineering. Develop existing partners and win new customers across Berlin, Brandenburg and surrounding regions. Mostly remote, 3+ years B2B/B2G sales. Company car, 30 days holiday.','Berlin / Brandenburg · Remote','','',NULL,NULL,'GBP','Full Time','Sales & Marketing','["Remote"]',1,NULL,NULL,'https://www.arbeitnow.com/jobs/companies/ing-plus-ag/account-sales-manager-ostdeutschland-furth-318191',strftime('%s','now','-7 hours'),strftime('%s','now'),strftime('%s','now'),'live',0),
('seed:8','arbeitnow','8','Office & HR Manager','Fritz Wellhöfer GmbH','Central role in office organisation and HR. Manage all HR processes from onboarding to offboarding, contracts, recruiting support, payroll prep. Permanent full-time position with holiday and Christmas bonuses, flexible hours, family-friendly.','Ansbach, Germany','','',NULL,NULL,'GBP','Full Time','Human Resources','[]',0,49.3,10.57,'https://www.arbeitnow.com/jobs/companies/fritz-wellhofer-gmbh-co-kg/office-hr-managerin-sachsen-bei-ansbach-432784',strftime('%s','now','-8 hours'),strftime('%s','now'),strftime('%s','now'),'live',0),
('seed:9','arbeitnow','9','Product Manager (Experienced)','bedrop','Fast-growing e-commerce company in health/natural products. Own the product lifecycle, run market and competitor analyses, support pricing and positioning, work closely with marketing, design, purchasing and logistics. Long-term scale-up perspective.','Mannheim, Germany','','',NULL,NULL,'GBP','Full Time','Sales & Marketing','[]',0,49.4875,8.466,'https://www.arbeitnow.com/jobs/companies/bedrop/produktmanager-berufserfahren-mannheim-234542',strftime('%s','now','-9 hours'),strftime('%s','now'),strftime('%s','now'),'live',0),
('seed:10','arbeitnow','10','Network Manager – Photonics','EurA AG','International innovation and funding consultancy. Identify technology and market potential, advise clients on innovative projects, build and steer photonics innovation networks, run workshops and events. Physics degree (Master/PhD) ideal; graduates welcome.','Ellwangen, Germany','','',NULL,NULL,'GBP','Full Time','Engineering','[]',0,48.961,10.13,'https://www.arbeitnow.com/jobs/companies/eura-ag/netzwerkmanager-photonik-ellwangen-23866',strftime('%s','now','-10 hours'),strftime('%s','now'),strftime('%s','now'),'live',0),
('seed:11','arbeitnow','11','Customer Advisor – Accounting Automation (Remote)','Finmatics GmbH','Finmatics builds ''Fin'', an AI accountant. As a customer advisor you implement solutions, train users and key users, optimise their processes and ensure the software is used to best effect. 100% remote in Germany. Min. salary €50,000.','Germany · Remote','','€50,000+',NULL,NULL,'GBP','Full Time','Customer Service','["Remote"]',1,NULL,NULL,'https://www.arbeitnow.com/jobs/companies/finmatics-gmbh/kundenberater-fur-buchhaltungsautomatisierung-remote-munich-341691',strftime('%s','now','-11 hours'),strftime('%s','now'),strftime('%s','now'),'live',0),
('seed:12','arbeitnow','12','CAD Design & 3D Print Intern (MedTech)','Think3DDD','Award-winning Berlin startup in 3D scanning, 3D printing and medical technology. Combine CAD design (Fusion 360, Tinkercad, Blender) with FDM 3D printing to build patient-specific orthopaedic parts. Hands-on, real products, flexible hours.','Berlin-Adlershof, Germany','','Unpaid (mandatory)',NULL,NULL,'GBP','Internship','Engineering','[]',0,52.43,13.53,'https://www.arbeitnow.com/jobs/companies/think3ddd-gbr/pflichtpraktikum-cad-design-fdm-3d-druck-open-source-tools-medtech-startup-berlin-410050',strftime('%s','now','-12 hours'),strftime('%s','now'),strftime('%s','now'),'live',0);
